name: Android Ci Release
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "README_en-US.md"
      - "doc/*"
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"
      - uses: gradle/gradle-build-action@v2
      - run:
          ./gradlew assemble

      - name: Sign Release APK
        if: success()
        id: sign_release
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: ./app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Sign Beta APK
        if: success()
        id: sign_beta
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: ./app/build/outputs/apk/beta
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Sign Canary APK
        if: success()
        id: sign_canary
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: ./app/build/outputs/apk/canary
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Sign Debug APK
        if: success()
        id: sign_debug
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: ./app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Upload Release APK
        uses: actions/upload-artifact@v2
        with:
          name: Cemiuiler release
          path: ${{ steps.sign_release.outputs.signedReleaseFile }}

      - name: Upload Beta APK
        uses: actions/upload-artifact@v2
        with:
          name: Cemiuiler debug
          path: ${{ steps.sign_beta.outputs.signedReleaseFile }}

      - name: Upload Canary APK
        uses: actions/upload-artifact@v2
        with:
          name: Cemiuiler debug
          path: ${{ steps.sign_canary.outputs.signedReleaseFile }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: Cemiuiler debug
          path: ${{ steps.sign_debug.outputs.signedReleaseFile }}

      - name: Upload Release Mapping
        uses: actions/upload-artifact@v2
        with:
          name: Cemiuiler mapping
          path: ./app/build/outputs/mapping/release/mapping.txt

      - name: Post to channel
        if: contains(github.event.head_commit.message, '[skip post]') == false
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          RELEASE: ${{ steps.sign_release.outputs.signedReleaseFile }}
          BETA: ${{ steps.sign_beta.outputs.signedReleaseFile }}
          CANARY: ${{ steps.sign_canary.outputs.signedReleaseFile }}
          DEBUG: ${{ steps.sign_debug.outputs.signedReleaseFile }}
          COMMIT_MESSAGE: |+
            Github CI
            ```
            ${{ github.event.head_commit.message }}
            ```
        run: |
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Frelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Fdebug%22%2C%22parse_mode%22%3A%22MarkdownV2%22%2C%22caption%22%3A${ESCAPED}%7D%5D" -F release="@$RELEASE" -F beta="@$BETA" -F canary="@$CANARY" -F debug="@$DEBUG"